/* eslint-disable */
/*Generated by GenDocu.com*/
// source: main.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.v1.ExampleMessage1', null, global);
goog.exportSymbol('proto.v1.ExampleMessage2', null, global);
goog.exportSymbol('proto.v1.ExampleMessage2.ExampleNested', null, global);
goog.exportSymbol('proto.v1.ReturnType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.ExampleMessage1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v1.ExampleMessage1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.ExampleMessage1.displayName = 'proto.v1.ExampleMessage1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.ExampleMessage2 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v1.ExampleMessage2, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.ExampleMessage2.displayName = 'proto.v1.ExampleMessage2';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.ExampleMessage2.ExampleNested = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v1.ExampleMessage2.ExampleNested, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.ExampleMessage2.ExampleNested.displayName = 'proto.v1.ExampleMessage2.ExampleNested';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.ReturnType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v1.ReturnType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.ReturnType.displayName = 'proto.v1.ReturnType';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.ExampleMessage1.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.ExampleMessage1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.ExampleMessage1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage1.toObject = function(includeInstance, msg) {
  var f, obj = {
    mystring: jspb.Message.getFieldWithDefault(msg, 1, ""),
    optionalBool: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    regularBool: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.ExampleMessage1}
 */
proto.v1.ExampleMessage1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.ExampleMessage1;
  return proto.v1.ExampleMessage1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.ExampleMessage1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.ExampleMessage1}
 */
proto.v1.ExampleMessage1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMystring(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOptionalBool(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRegularBool(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.ExampleMessage1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.ExampleMessage1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.ExampleMessage1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRegularBool();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string MyString = 1;
 * @return {string}
 */
proto.v1.ExampleMessage1.prototype.getMystring = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.ExampleMessage1} returns this
 */
proto.v1.ExampleMessage1.prototype.setMystring = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v1.ExampleMessage1} returns this
 */
proto.v1.ExampleMessage1.prototype.clearMystring = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.ExampleMessage1.prototype.hasMystring = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool optional_bool = 2;
 * @return {boolean}
 */
proto.v1.ExampleMessage1.prototype.getOptionalBool = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v1.ExampleMessage1} returns this
 */
proto.v1.ExampleMessage1.prototype.setOptionalBool = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v1.ExampleMessage1} returns this
 */
proto.v1.ExampleMessage1.prototype.clearOptionalBool = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.ExampleMessage1.prototype.hasOptionalBool = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool regular_bool = 4;
 * @return {boolean}
 */
proto.v1.ExampleMessage1.prototype.getRegularBool = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v1.ExampleMessage1} returns this
 */
proto.v1.ExampleMessage1.prototype.setRegularBool = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.ExampleMessage2.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.ExampleMessage2.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.ExampleMessage2} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage2.toObject = function(includeInstance, msg) {
  var f, obj = {
    myint: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nested: (f = msg.getNested()) && proto.v1.ExampleMessage2.ExampleNested.toObject(includeInstance, f),
    m3: (f = msg.getM3()) && proto.v1.ExampleMessage1.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.ExampleMessage2}
 */
proto.v1.ExampleMessage2.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.ExampleMessage2;
  return proto.v1.ExampleMessage2.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.ExampleMessage2} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.ExampleMessage2}
 */
proto.v1.ExampleMessage2.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMyint(value);
      break;
    case 2:
      var value = new proto.v1.ExampleMessage2.ExampleNested;
      reader.readMessage(value,proto.v1.ExampleMessage2.ExampleNested.deserializeBinaryFromReader);
      msg.setNested(value);
      break;
    case 3:
      var value = new proto.v1.ExampleMessage1;
      reader.readMessage(value,proto.v1.ExampleMessage1.deserializeBinaryFromReader);
      msg.setM3(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.ExampleMessage2.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.ExampleMessage2.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.ExampleMessage2} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage2.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMyint();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNested();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.v1.ExampleMessage2.ExampleNested.serializeBinaryToWriter
    );
  }
  f = message.getM3();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.v1.ExampleMessage1.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.ExampleMessage2.ExampleNested.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.ExampleMessage2.ExampleNested} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage2.ExampleNested.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.ExampleMessage2.ExampleNested}
 */
proto.v1.ExampleMessage2.ExampleNested.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.ExampleMessage2.ExampleNested;
  return proto.v1.ExampleMessage2.ExampleNested.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.ExampleMessage2.ExampleNested} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.ExampleMessage2.ExampleNested}
 */
proto.v1.ExampleMessage2.ExampleNested.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.ExampleMessage2.ExampleNested.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.ExampleMessage2.ExampleNested} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ExampleMessage2.ExampleNested.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes data = 1;
 * @return {!(string|Uint8Array)}
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes data = 1;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.v1.ExampleMessage2.ExampleNested} returns this
 */
proto.v1.ExampleMessage2.ExampleNested.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional int32 MyInt = 1;
 * @return {number}
 */
proto.v1.ExampleMessage2.prototype.getMyint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.v1.ExampleMessage2} returns this
 */
proto.v1.ExampleMessage2.prototype.setMyint = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional ExampleNested nested = 2;
 * @return {?proto.v1.ExampleMessage2.ExampleNested}
 */
proto.v1.ExampleMessage2.prototype.getNested = function() {
  return /** @type{?proto.v1.ExampleMessage2.ExampleNested} */ (
    jspb.Message.getWrapperField(this, proto.v1.ExampleMessage2.ExampleNested, 2));
};


/**
 * @param {?proto.v1.ExampleMessage2.ExampleNested|undefined} value
 * @return {!proto.v1.ExampleMessage2} returns this
*/
proto.v1.ExampleMessage2.prototype.setNested = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v1.ExampleMessage2} returns this
 */
proto.v1.ExampleMessage2.prototype.clearNested = function() {
  return this.setNested(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.ExampleMessage2.prototype.hasNested = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ExampleMessage1 m3 = 3;
 * @return {?proto.v1.ExampleMessage1}
 */
proto.v1.ExampleMessage2.prototype.getM3 = function() {
  return /** @type{?proto.v1.ExampleMessage1} */ (
    jspb.Message.getWrapperField(this, proto.v1.ExampleMessage1, 3));
};


/**
 * @param {?proto.v1.ExampleMessage1|undefined} value
 * @return {!proto.v1.ExampleMessage2} returns this
*/
proto.v1.ExampleMessage2.prototype.setM3 = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v1.ExampleMessage2} returns this
 */
proto.v1.ExampleMessage2.prototype.clearM3 = function() {
  return this.setM3(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.ExampleMessage2.prototype.hasM3 = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.ReturnType.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.ReturnType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.ReturnType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ReturnType.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.ReturnType}
 */
proto.v1.ReturnType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.ReturnType;
  return proto.v1.ReturnType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.ReturnType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.ReturnType}
 */
proto.v1.ReturnType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.ReturnType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.ReturnType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.ReturnType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.ReturnType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.v1);
